Remaining precompiles v2
FhenixProtocol/go-tfhe pull request #21
Opened 2023-11-29 03:17 UTC by eshelB

2023-11-29 09:31 UTC, Cashmaney approved these changes

2023-11-30 13:49 UTC, liorbond requested changes

2023-11-30 13:49 UTC, liorbond commented on internal/api/amd64/lib.go
> +	// todo why is this here?
Please speak with @Cashmaney whether delete this code or add your ops

2023-11-30 13:49 UTC, liorbond commented on internal/api/types.go
> +	// todo add more ops
what ops should we add?

2023-11-30 13:49 UTC, liorbond commented on libtfhe-wrapper/src/api/ffi/api.rs
> +    // todo remaining ops
what ops?

2023-11-30 13:49 UTC, liorbond commented on libtfhe-wrapper/src/api/ffi/api.rs
> +            // todo add remaining ops
what ops?

2023-11-30 13:49 UTC, liorbond commented on libtfhe-wrapper/src/math.rs
> +        // todo add remaining ops
what ops?

2023-12-03 16:05 UTC, merged