Optimize select
FhenixProtocol/go-tfhe pull request #32
Opened 2024-01-24 16:58 UTC by Cashmaney

2024-01-24 19:05 UTC, liorbond requested changes

2024-01-24 19:21 UTC, Cashmaney commented on libtfhe-wrapper/src/api/ffi/api.rs
> +    let mut mask = trivial_encrypt_safe(0, uint_type)?;
It's inside the rust code - this encrypt takes orders of magnitude less time then everything else

2024-01-24 19:22 UTC, Cashmaney commented on internal/api/amd64/lib.go
> +	return result, nil
Ah, I'll revert. Did this to do some microbenches

2024-01-24 19:23 UTC, Cashmaney commented on libtfhe-wrapper/src/api/ffi/api.rs
> +    // Subtract the control slice from the mask, effectively creating an encryption of (0 - control).
I put the main logic in the function desc as well, but sure

2024-01-24 20:51 UTC, liorbond commented on libtfhe-wrapper/src/api/ffi/api.rs
> +    let mut mask = trivial_encrypt_safe(0, uint_type)?;
I know but would it be easy to optimize it? it will probably reduce 3ms but why not :P

2024-01-24 20:52 UTC, liorbond approved these changes

2024-01-24 21:44 UTC, merged

2024-01-29 14:22 UTC, eshelB reviewed
Nice!